language: rust
rust:
  - stable
  - beta
  - nightly

before_script:
  - wget "https://download.libsodium.org/libsodium/releases/LATEST.tar.gz"
  - tar -xzvf LATEST.tar.gz
  - cd libsodium-stable && ./configure --prefix=/usr && make && sudo make install

matrix:
  allow_failures:
    - rust: nightly